"""Multi-Account Reconciliation Dashboard — Streamlit UI

Upload multiple reconciliation summary files (Excel or CSV archives) to generate
a consolidated dashboard showing:
  - Overall reconciliation metrics across all accounts
  - Per-account reconciliation rate breakdown
  - Account matrix with volume and amount details
  - Trend analysis (when multiple snapshots uploaded)

Run: streamlit run app.py
"""

from __future__ import annotations

import logging
import os
from datetime import datetime

import streamlit as st

from backend.core.dashboard_generator import generate_dashboard, parse_reconciliation_file
from backend.core.errors import ReconError

logging.basicConfig(
    level=os.environ.get("RECON_LOG_LEVEL", "INFO"),
    format="%(asctime)s %(levelname)s %(name)s :: %(message)s",
)

BRAND_GREEN = "#60BB46"
CHARCOAL = "#1F2937"

st.set_page_config(
    page_title="Reconciliation Dashboard Generator",
    page_icon="📊",
    layout="wide",
)

st.markdown(
    f"""
    <style>
      .stApp {{ background: #F8FAFC; }}
      .recon-banner {{
        background: {BRAND_GREEN}; color: #fff; padding: 18px 24px; border-radius: 10px;
        display: flex; justify-content: space-between; align-items: center; margin-bottom: 18px;
      }}
      .recon-banner h1 {{ font-size: 1.35rem; margin: 0; font-weight: 700; letter-spacing: -0.01em; }}
      .recon-badge {{ background: rgba(255,255,255,.22); padding: 6px 14px; border-radius: 999px;
                      font-size: .82rem; font-weight: 600; }}
      .step {{ color: {CHARCOAL}; font-weight: 700; font-size: .78rem; letter-spacing: .09em;
               text-transform: uppercase; margin: 14px 0 4px; }}
      .account-card {{
        background: #fff; border: 1px solid #E2E8F0; border-radius: 8px;
        padding: 12px 16px; margin: 6px 0;
      }}
      .account-name {{ font-weight: 700; color: {CHARCOAL}; }}
      .account-metric {{ font-size: .85rem; color: #64748B; }}
      .metric-ok {{ color: {BRAND_GREEN}; font-weight: 700; }}
      .metric-warning {{ color: #F59E0B; font-weight: 700; }}
      .stButton > button {{ background: {BRAND_GREEN}; color: #fff; border: 0; border-radius: 8px;
                            padding: .6rem 1.4rem; font-weight: 700; }}
      .stDownloadButton > button {{ background: {CHARCOAL}; color: #fff; border: 0; border-radius: 8px;
                                    font-weight: 700; }}
    </style>
    """,
    unsafe_allow_html=True,
)


def banner() -> None:
    st.markdown(
        f"""<div class="recon-banner">
              <h1>📊 Multi-Account Reconciliation Dashboard</h1>
              <span class="recon-badge">Aggregate View</span>
            </div>""",
        unsafe_allow_html=True,
    )


def main() -> None:
    banner()
    
    st.markdown(
        """
        Upload reconciliation summary files (Excel .xlsx or CSV .zip archives) from multiple accounts 
        to generate a consolidated dashboard showing overall performance, per-account breakdowns, 
        and trend analysis.
        """)
    
    # ── Step 1 · Upload Files ────────────────────────────────────────────────
    st.markdown('<div class="step">Step 1 · Upload Reconciliation Files</div>', unsafe_allow_html=True)
    
    uploaded_files = st.file_uploader(
        "Upload one or more reconciliation summary files",
        type=["xlsx", "xls", "zip"],
        accept_multiple_files=True,
        help="Upload Excel workbooks (.xlsx) or CSV ZIP archives (.zip) generated by the reconciliation engine"
    )
    
    if not uploaded_files:
        st.info("📤 Upload at least one reconciliation file to generate the dashboard.\n\n"
                "**Supported formats:**\n"
                "- Excel workbooks (.xlsx, .xls) — from 'Excel (Legacy)' output\n"
                "- CSV archives (.zip) — from 'CSV (Lightweight)' output")
        return
    
    st.success(f"✓ {len(uploaded_files)} file(s) uploaded")
    
    # ── Step 2 · Preview Parsed Data ─────────────────────────────────────────
    st.markdown('<div class="step">Step 2 · Preview Account Data</div>', unsafe_allow_html=True)
    
    parsed_accounts = []
    parse_errors = []
    
    with st.spinner("Parsing uploaded files..."):
        for uploaded_file in uploaded_files:
            try:
                # Auto-extract account name from filename (e.g., "recon_fonepay_20260922.xlsx" -> "Fonepay")
                filename = uploaded_file.name
                account_name = filename.replace("recon_", "").replace(".xlsx", "").replace(".zip", "")
                account_name = account_name.rsplit("_", 1)[0]  # Remove date suffix if present
                account_name = account_name.replace("_", " ").title()
                
                # Parse the file
                raw_bytes = uploaded_file.getvalue()
                snapshot = parse_reconciliation_file(raw_bytes, account_name)
                parsed_accounts.append(snapshot)
            except Exception as exc:
                parse_errors.append((uploaded_file.name, str(exc)))
                logging.exception(f"Failed to parse {uploaded_file.name}")
    
    if parse_errors:
        st.warning(f"⚠️ Failed to parse {len(parse_errors)} file(s):")
        for filename, error in parse_errors:
            with st.expander(f"❌ {filename}", expanded=False):
                st.code(error, language="text")
                
                # Provide helpful hints based on error type
                if "summary.csv" in error.lower():
                    st.caption("💡 **Tip**: This file appears to be an Excel workbook, not a CSV archive. "
                             "The system should auto-detect this. Please report this as a bug if it persists.")
                elif "Summary" in error and "not found" in error.lower():
                    st.caption("💡 **Tip**: This file doesn't contain a 'Summary' sheet. "
                             "Make sure you're uploading a reconciliation output file, not raw data.")
                else:
                    st.caption("💡 **Tip**: Try re-downloading this file or re-running the reconciliation.")
    
    if not parsed_accounts:
        st.error("No files could be parsed successfully. Please check your files and try again.")
        return
    
    # Display parsed account cards
    st.write(f"**Successfully parsed {len(parsed_accounts)} account(s):**")
    
    for account in sorted(parsed_accounts, key=lambda a: a.account_name):
        recon_class = "metric-ok" if account.recon_rate >= 99.9 else "metric-warning"
        flag = "✓ OK" if account.recon_rate >= 99.9 else "⚠ Review"
        
        st.markdown(
            f"""
            <div class="account-card">
                <div class="account-name">{account.account_name} <span class="{recon_class}">{flag}</span></div>
                <div class="account-metric">
                    Recon Rate: <b>{account.recon_rate:.2f}%</b> | 
                    Matched: <b>{account.matched:,}</b> | 
                    CNP-only: <b>{account.cnp_only:,}</b> | 
                    CPT-only: <b>{account.cpt_only:,}</b>
                </div>
            </div>
            """,
            unsafe_allow_html=True,
        )
    
    # ── Step 3 · Dashboard Configuration ─────────────────────────────────────
    st.markdown('<div class="step">Step 3 · Configure Dashboard</div>', unsafe_allow_html=True)
    
    col1, col2 = st.columns(2)
    
    with col1:
        snapshot_date = st.date_input(
            "Snapshot Date",
            value=datetime.now(),
            help="The date for this reconciliation snapshot"
        )
    
    with col2:
        # Future enhancement: allow multiple date uploads for trend analysis
        st.caption("Multi-day trend analysis: Coming soon")
    
    # ── Step 4 · Generate Dashboard ──────────────────────────────────────────
    st.markdown('<div class="step">Step 4 · Generate Dashboard</div>', unsafe_allow_html=True)
    
    if not st.button("Generate Dashboard", type="primary"):
        return
    
    try:
        with st.spinner("Generating consolidated dashboard..."):
            # Prepare snapshot files list
            snapshot_files = [
                (uploaded_file.getvalue(), account.account_name)
                for uploaded_file, account in zip(uploaded_files, parsed_accounts)
            ]
            
            # Generate dashboard
            dashboard_bytes = generate_dashboard(
                snapshot_files=snapshot_files,
                snapshot_date=snapshot_date.strftime("%Y-%m-%d"),
            )
        
        st.success("✓ Dashboard generated successfully!")
        
        # ── Step 5 · Summary & Download ──────────────────────────────────────
        st.markdown('<div class="step">Step 5 · Summary & Download</div>', unsafe_allow_html=True)
        
        # Display aggregate metrics
        total_accounts = len(parsed_accounts)
        total_our = sum(a.our_count for a in parsed_accounts)
        total_matched = sum(a.matched for a in parsed_accounts)
        overall_recon_rate = 100.0 * total_matched / max(total_our, 1)
        accounts_flagged = sum(1 for a in parsed_accounts if a.recon_rate < 99.9)
        
        k1, k2, k3, k4 = st.columns(4)
        k1.metric("Total Accounts", f"{total_accounts}")
        k2.metric("Overall Recon Rate", f"{overall_recon_rate:.2f}%")
        k3.metric("Total Volume", f"{total_our:,}")
        k4.metric("Accounts Flagged", f"{accounts_flagged}")
        
        # Download button
        filename = f"recon_dashboard_{snapshot_date.strftime('%Y%m%d')}.xlsx"
        st.download_button(
            "⬇ Download Dashboard Workbook (.xlsx)",
            data=dashboard_bytes,
            file_name=filename,
            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        )
        
        st.info(
            "💡 **Dashboard Contents:**\n"
            "- Overview: Key metrics and snapshot summary\n"
            "- Recon_Rate_By_Account: Per-account reconciliation rates\n"
            "- Account_Matrix: Detailed volume and amount breakdown\n"
            "- (More sheets coming soon: Status breakdown, trends, unmatched details)"
        )
    
    except Exception as exc:
        logging.exception("Dashboard generation failed")
        st.error(f"Failed to generate dashboard: {type(exc).__name__}: {exc}")


if __name__ == "__main__":
    main()
